### ISSUE TITLE
Exporting records does not work as expected

### ISSUE THREAD

**Issue by kostobog** [kbss-cvut/record-manager-ui#185]
@grotskat:
> Export u Vietnamu funguje, ale soubor je bez dat. Export u AVA nefunguje.

**Comment by kostobog** [comment]
Error related to export not downloading any file:
```
prod-ava-record-manager-server  | 17-07-2024 07:47:48.526 [] [http-nio-8080-exec-10] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/record-manager] threw exception [Request processing failed: java.lang.ClassCastException: class cz.cvut.kbss.ontodriver.model.LangString cannot be cast to class java.lang.Number (cz.cvut.kbss.ontodriver.model.LangString is in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @5305068a; java.lang.Number is in module java.base of loader 'bootstrap')] with root cause
prod-ava-record-manager-server  | java.lang.ClassCastException: class cz.cvut.kbss.ontodriver.model.LangString cannot be cast to class java.lang.Number (cz.cvut.kbss.ontodriver.model.LangString is in unnamed module of loader org.springframework.boot.loader.launch.LaunchedClassLoader @5305068a; java.lang.Number is in module java.base of loader 'bootstrap')
prod-ava-record-manager-server  |       at cz.cvut.kbss.jopa.oom.converter.ToIntegerConverter.convertToAttribute(ToIntegerConverter.java:31)
prod-ava-record-manager-server  |       at cz.cvut.kbss.jopa.oom.converter.ToIntegerConverter.convertToAttribute(ToIntegerConverter.java:20)
prod-ava-record-manager-server  |       at cz.cvut.kbss.jopa.query.mapper.FieldResultMapper.lambda$resolveValue$1(FieldResultMapper.java:93)
prod-ava-record-manager-server  |       at java.base/java.util.Optional.map(Optional.java:260)
prod-ava-record-manager-server  |       at cz.cvut.kbss.jopa.query.mapper.FieldResultMapper.resolveValue(FieldResultMapper.java:93)
prod-ava-record-manager-server  |       at cz.cvut.kbss.jopa.query.mapper.FieldResultMapper.lambda$map$0(FieldResultMapper.java:73)
prod-ava-record-manager-server  |       at java.base/java.util.Optional.ifPresent(Optional.java:178)

```

**Comment by kostobog** [comment]
@blcham 
### PR testing
Locally on big dataset. Class cast exception reproduced locally by setting `18. Number of overhauls of defective equipment` to 1 and trying to export.
- exception does not occur and all records are exported in excel.

Testing on kbss PR-59 deployed on KBSS. The following scenarios work as expected:
- export all records as admin in ava
- export all records as admin in Vietnam
- export all records as user in Vietnam
